services:
  postgres:
    image: postgres:16
    container_name: data-louna-db
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: data-louna-redis
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
